### ISSUE TITLE
The arrows seem to be not working when capslock is on

### ISSUE THREAD

**Issue by Lee-W** [beeware/podium#27]
## Expected behavior
When pressing the arrows, the slide to jump to previous/next pages even when the capslock is turn on.

## Actual behavior
The slide does not jump to previous/next pages when pressing the arrows with capslock is on.

## Testing Environment

* Operation System: macOS 10.14.4
* Python 3.7.3

**Comment by freakboy3742** [comment]
I haven't seen this one specifically, but it doesn't surprise me at all. I've definitely observed a similar problem with refresh *requiring* the shift (cmd-shift-R, not just cmd-r). I'm pretty sure it's due to the keyboard code scanning.

The problem will almost certainly stem from the on_key_press handling in deck.py/SlideDeck.

**Comment by Lee-W** [comment]
This problem seems to be caused by a typo in toga project.

[src/cocoa/toga_cocoa/keys.py](https://github.com/beeware/toga/blob/96c50882571d02b69c7bfba8f013f89e65f41831/src/cocoa/toga_cocoa/keys.py#L122)

**Comment by Lee-W** [comment]
Since the PR to [toga](https://github.com/beeware/toga) is merged, it should work after toga is updated.
Close this issue.
